### ISSUE TITLE
Eleventy github actions tutorial fails

### ISSUE THREAD

**Issue by geotheory** [maartentibau/maarten.be#1]
Hi Maarten

Your [tutorial](https://maarten.be/blog/20220730/how-to-deploy-your-eleventy-website-to-github-pages-with-github-actions/) is failing for me at first `npm run start` with:

```
npm run start

> eleventy-sample@1.0.0 start
> npm run watch:eleventy & npm run watch:sass


> eleventy-sample@1.0.0 watch:sass
> sass src/static/scss:public/static/css --watch


> eleventy-sample@1.0.0 watch:eleventy
> eleventy --serve

Sass is watching for changes. Press Ctrl-C to stop.

[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] TemplateLayoutPathResolver directory does not exist for base.njk: _includes (via Error)
[11ty]
[11ty] Original error stack trace: Error: TemplateLayoutPathResolver directory does not exist for base.njk: _includes
[11ty]     at TemplateLayoutPathResolver.findFileName (/Users/username/Documents/Personal/SEN/eleventy-sample/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:105:13)
[11ty]     at TemplateLayoutPathResolver.init (/Users/username/Documents/Personal/SEN/eleventy-sample/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:72:28)
[11ty]     at new TemplateLayoutPathResolver (/Users/username/Documents/Personal/SEN/eleventy-sample/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:25:10)
[11ty]     at new TemplateLayout (/Users/username/Documents/Personal/SEN/eleventy-sample/node_modules/@11ty/eleventy/src/TemplateLayout.js:17:24)
[11ty]     at Function.getTemplate (/Users/username/Documents/Personal/SEN/eleventy-sample/node_modules/@11ty/eleventy/src/TemplateLayout.js:47:18)
[11ty]     at Template.getLayout (/Users/username/Documents/Personal/SEN/eleventy-sample/node_modules/@11ty/eleventy/src/Template.js:132:37)
[11ty]     at Template.getData (/Users/username/Documents/Personal/SEN/eleventy-sample/node_modules/@11ty/eleventy/src/Template.js:417:27)
[11ty]     at async Template.getTemplateMapEntries (/Users/username/Documents/Personal/SEN/eleventy-sample/node_modules/@11ty/eleventy/src/Template.js:1087:33)
[11ty]     at async TemplateMap.add (/Users/username/Documents/Personal/SEN/eleventy-sample/node_modules/@11ty/eleventy/src/TemplateMap.js:59:21)
[11ty]     at async Promise.all (index 0)
[11ty] Wrote 0 files in 0.11 seconds (v1.0.1)
```

Any idea why?  Pretty sure I've followed your steps to the letter.

**Comment by maartentibau** [comment]
Hi @geotheory , thanks for creating this issue! 🙏 

You are indeed correct. I made a mistake in the blog stating that the `.eleventy.js` needs to be put in the `src` folder, which is incorrect and should be the `root` folder.

I'll create a PR to fix the issue in the blog post.

Sorry for the inconvenience.

**Comment by maartentibau** [comment]
Fixed: https://github.com/maartentibau/maarten.be/pull/2

**Comment by geotheory** [comment]
Sweet thanks. Will test when I have a mo :)

**Comment by geotheory** [comment]
OK I've tried to complete the tutorial but my github actions builds are failing.   I think the `build-and-deploy.yml` requires more customisation than you have documented - e.g: `peaceiris/actions-gh-pages@v3` is not my project and when I correct the path (to `geotheory/my-eleventy-website`) I don't know what to sub for `@v3`

Testing with `geotheory/my-eleventy-website@master` the build fails with :

`Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/_actions/geotheory/my-eleventy-website/master'. Did you forget to run actions/checkout before running your local action?`

Any idea what's going wrong here?

----------------------

TBA the documentation you link to [ACTIONS_DEPLOY_KEY](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-ssh-deploy-key) is slightly out of date because the interface looks different now. But I think I managed to set the keys up correctly, and set the process to build from Github Actions.

**Comment by maartentibau** [comment]
Hi @geotheory,

`peaceiris/actions-gh-pages@v3` is not something that needs to be changed. Because it points to a plugin: https://github.com/peaceiris/actions-gh-pages

That plugin is being used by Github Actions, so there is no need to change this.

The tutorial on how to create and setup your `ACTIONS_DEPLOY_KEY` is still valid, but indeed the screenshots are a bit outdated.  As you can see in the URL of that tutorial, it points also to `https://github.com/peaceiris/actions-gh-pages` 😉 

One thing I noticed, I need to adapt this in the blog post. You need to put the`.yml` files in `.github/workflows` folder.

Once that is let the full build run, and go back to `settings —> pages` and select `gh-pages` as the branch. The build script will have automatically created that branch.

Select that branch and hit the save button, the build-and-deployment workflow will be auto triggered once again. That should do it!

**Comment by maartentibau** [comment]
I added the additional info in the blog post. Thanks for the help in pointing out the mistakes I overlooked 😄 🙏

**Comment by geotheory** [comment]
Hey @maartentibau thanks for the follow up.  OK I reverted `build-and-deploy.yaml` to original verison. And my yaml files were already in `.github/workflows`. But still I'm failing currently with `Action failed with "The process '/usr/bin/ssh-add' failed with exit code 1"`. My codebase is here in case there's an obvious deviation from your tutorial - https://github.com/geotheory/my-eleventy-website.

I did wonder why the `/public` folder is included in .gitignore. But I removed it and still got same fail..

**Comment by maartentibau** [comment]
The `/public` folder needs to be ignored, because it only used when you're building your Eleventy website locally. So there is no need to push this to GitHub.

I'm pretty sure you made a mistake in setting up your `secrets.ACTIONS_DEPLOY_KEY`.
What you could try in change the last line your `.yml` file to this:

`deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}`

replace it with

`github_token: ${{ secrets.GITHUB_TOKEN }}`

To use the `GITHUB_TOKEN` no setup should be needed, but as I read from the tutorial it might not always work out of the box, that is why I went with the `deploy_key` in the first place, but `github_token` is also supported, so maybe that might be a better choice after all.

**Comment by geotheory** [comment]
Success! Thanks very much Maarten you've been very helpful indeed :)

I like how this updates when content is edited in github. Bad practice I know, but it means a trusted editor can make changes without me.

**Comment by maartentibau** [comment]
Well .. actually the content only updates when you push changes to the `master` branch. Normally a `master` branch is protected and a direct push can never be done, only a `merge`.

This way content is never directly updated, but only updated when a merge happens with `master`. When I create new content I always try to do this in a separate branch, once done I merge it because you can test everything locally. For quick updates and fixes I due tend to push to `master` but I try to avoid this as much as possible.

**Comment by geotheory** [comment]
Of course you're right about when master branch is protected, but I don't think this is desirable for every project. It does appear to be the new commit rather than the 'push' that triggers the action. When I edit e.g. `my-eleventy-website/src/index.md` file (master branch) directly in Github with my browser it does automatically rebuild the site..

**Comment by maartentibau** [comment]
A `push` contains your `commits` 🙂 but you are correct, on every change you make on your `master` branch an new build will be done.

But you can specify in the `.yml` file a lot of stuff and limit when actions are triggered, the possibilities are quite advanced.

**Comment by geotheory** [comment]
Noted. Thanks again Maarten :)
